## CompassX configurations.
vaadin:
    servlet:
        productionMode: true
spring:
    profiles: prod
server:
    contextPath: /
com:
    ciminc:
        compass:
            compassBaseURL: https://webapp.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: https://fileservice.ciminc.com/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: dev
server:
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:12080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: ben
server:
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://10.49.5.240:7071/CompassMI
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: david
server:
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://10.49.5.84:9125/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: bill-work
server:
    port: 8084
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:12080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: bill-home
server:
    port: 8084
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:8080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
