## CompassX configurations.
vaadin:
    servlet:
        productionMode: true
spring:
    profiles: prod
server:
    contextPath: /
com:
    ciminc:
        compass:
            compassBaseURL: https://webapp.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: https://fileservice.ciminc.com/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: dev
server:
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:12080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: ben
server:
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://10.49.5.240:7071/CompassMI
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: david
server:
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://10.49.5.84:9125/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: bill-work
server:
    port: 8084
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:12080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: bill-home
server:
    port: 8084
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:8080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: gary
server:
    port: 8084
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://10.49.5.119:8080/CompassMI
            fileAttaching:
                serverUrl: http://10.49.5.119:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
vaadin:
    servlet:
        productionMode: true
spring:
    profiles: QA
server:
    port: 9090
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-qa-app.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: https://fileservice.ciminc.com/cim-file-service
        compassx:
            notificationsEnabled: false
---
vaadin:
    servlet:
        productionMode: true
spring:
    profiles: nightly
server:
    port: 9090
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://compassmi-nightly.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false

---
spring:
    profiles: autotest
server:
    port: 6060
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-autotest-app.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: demo
server:
    port: 9590
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-demo-app.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: QA-prior
server:
    port: 7070
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-qa-app-prior.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: snapshot
server:
    port: 5050
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-snapshot-app.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: thien
server:
    port: 8084
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:31947/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: julie
server:
    port: 8080
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:56218/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: brian
server:
    port: 8080
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:43001/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: brian-hotfix
server:
    port: 8080
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:12260/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: brian-hotfix
server:
    port: 8080
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:12260/CompassMI
        compassx:
            notificationsEnabled: false
            cimFileServiceUrl: http://localhost:8989/cim-file-service
---
vaadin:
    servlet:
        productionMode: true
spring:
    profiles: hotfix
server:
    port: 9191
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-qa-hotfix.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
vaadin:
    servlet:
        productionMode: true
spring:
    profiles: training
server:
    port: 9595
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: https://mi-qa-training.ciminc.com/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: jim
server:
    port: 16048
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:14080/CompassMI
            fileAttaching:
                serverUrl: http://localhost:8989/cim-file-service
        compassx:
            notificationsEnabled: false
---
spring:
    profiles: jim
server:
    port: 16048
    contextPath: /CompassMI/compassx-ui
com:
    ciminc:
        compass:
            compassBaseURL: http://localhost:14080/CompassMI
        compassx:
            notificationsEnabled: false
            cimFileServiceUrl: http://localhost:8989/cim-file-service